/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const func = () => {
  return process.env.NODE_ENV === 'development' ? 'drishti-3d/' : '';
}

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(func() + 'AB_Extra_mobile.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="AB_extra_mobile" geometry={nodes.AB_extra_mobile.geometry} material={materials.ab_extra_mobile} />
      </group>
    </group>
  )
}

useGLTF.preload(func() + 'AB_Extra_mobile.glb')
