/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const func = () => {
  return process.env.NODE_ENV === 'development' ? 'drishti-3d/' : '';
}

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(func() + 'robot2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[0, 0.82, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.05, -0.15, -0.05]}
      />
      <group position={[0.07, 1.52, 0]} rotation={[0, Math.PI / 2, 0]} scale={[-0.03, 0.03, 0.03]}>
        <mesh geometry={nodes.NurbsPath007.geometry} material={nodes.NurbsPath007.material} />
        <mesh geometry={nodes.NurbsPath007_1.geometry} material={nodes.NurbsPath007_1.material} />
        <mesh geometry={nodes.NurbsPath007_2.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.NurbsPath007_3.geometry} material={materials['Material.014']} />
      </group>
      <group position={[0.15, 1.4, -0.14]} rotation={[Math.PI / 2, 0.03, Math.PI / 2]} scale={[0.01, 0, 0.01]}>
        <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} />
        <mesh geometry={nodes.Cylinder008_1.geometry} material={nodes.Cylinder008_1.material} />
        <mesh geometry={nodes.Cylinder008_2.geometry} material={nodes.Cylinder008_2.material} />
      </group>
      <group position={[0, 0.88, -0.19]} rotation={[0, 0, 0.16]} scale={[-0.07, -0.05, 0.01]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube014_2.geometry} material={nodes.Cube014_2.material} />
        <mesh geometry={nodes.Cube014_3.geometry} material={nodes.Cube014_3.material} />
      </group>
      <group position={[-0.03, 1.42, -0.19]} rotation={[-0.17, 0, 0]} scale={[-0.04, 0, 0.05]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube015_3.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube015_4.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube015_5.geometry} material={nodes.Cube015_5.material} />
      </group>
    </group>
  )
}

useGLTF.preload(func() + 'robot2.glb')
