/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const func = () => {
  return process.env.NODE_ENV === 'development' ? 'drishti-3d/' : '';
}

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(func() + 'room_4.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube008.geometry} material={materials['1_01.007']} />
      <mesh geometry={nodes.Cube008_1.geometry} material={materials['1_02.007']} />
      <mesh geometry={nodes.Cube008_2.geometry} material={materials['1_03.007']} />
    </group>
  )
}

useGLTF.preload(func() + 'room_4.glb')
