/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


const func = () => {
  return process.env.NODE_ENV === 'development' ? 'drishti-3d/' : '';
}

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(func() + 'room_3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials['1_01.002']} />
      <mesh geometry={nodes.Cube002_1.geometry} material={materials['1_02.002']} />
      <mesh geometry={nodes.Cube002_2.geometry} material={materials['1_03.002']} />
    </group>
  )
}

useGLTF.preload(func() + 'room_3.glb')
