/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const func = () => {
  return process.env.NODE_ENV === 'development' ? 'drishti-3d/' : '';
}

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(func() + 'ROBOT TEST_1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[1.54, 0, Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder008.geometry} material={materials['Material.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder008_1.geometry} material={materials['Material.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder008_2.geometry} material={materials['Material.009']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder008_3.geometry} material={materials['Material.008']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder008_4.geometry} material={materials['Material.010']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder008_5.geometry} material={materials['Material.007']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder008_6.geometry} material={materials['Material.012']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder008_7.geometry} material={materials['Material.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder008_8.geometry} material={materials['Material.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder008_9.geometry} material={materials['Material.013']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder008_10.geometry} material={materials['Material.014']} />
      </group>
    </group>
  )
}

useGLTF.preload(func() + 'ROBOT TEST_1.glb')
